### ISSUE TITLE
problem with registry keys

### ISSUE THREAD

**Issue by BrendanBall** [jeffgrunewald/stargate#21]
Hi

We're looking to use this library except there's 2 small issues regarding registry keys
1. Atoms are used as registry keys. We intend to create many short lived topics so converting a topic name into an atom is a problem. 
2. The registry key is not part of the public api, however it's the only way to reference a producer when using the provided supervisor. In the docs it says `Once the producer is running, pass messages to the client by pid or by the named registry entry` , but I had to find how to construct the key by digging into the source code to find `:"sg_prod_#{tenant}_#{namespace}_#{topic}"`

1. could be solved by refactoring to keep the topic as a string in the registry key
2. could be solved either by providing a public a public function to construct the key or allow the library consumer to instead specify a function for constructing the registry keys. I think this second option is better because it doesn't break backwards compatibility for existing users relying on the hard coded  key `:"sg_prod_#{tenant}_#{namespace}_#{topic}"`  while also allowing users to solve 1. by providing a custom key that could for example do `{:producer, :"#{tenant}", :#{namespace}, topic}`.

Let me know what you think :)

**Comment by jeffgrunewald** [comment]
Hey Brendan,

Thanks for you thoughts on this. In general, I'm not opposed to either of these suggestions and reducing the reliance on atoms for producer and consumer/reader names is good goal.

I like the suggestion of the names being 4-tuples; if I understand your suggestion I think we'd want the first element of the tuple to be the type of process as an atom (`:producer`, `:consumer`, `:reader`) and the remaining three elements being the tenant, namespace, and topic as simple strings.

If that's the case, can you elaborate on your suggestion for preserving backward compatibility for users who are already using the atom-based process names? Are you suggesting a simple helper function that translates the existing atom names to the proposed 4-tuple? This shouldn't be difficult given those atoms are constructed to follow a pre-determined pattern. Something like:

```
def produce(producer, messages) when is_atom(producer) do
  with {:producer, tenant, namespace, topic} = producer_tuple <- parse_atom_name(producer) do
    produce(producer_tuple, messages)
  end
end

defp parse_atom_name(process) do
  [tenant, namespace, topic] =
    process
    |> to_string()
    |> Enum.take(-3)

  {:producer, tenant, namespace, topic}
end
```

Does this align with your intentions?

**Comment by jeffgrunewald** [comment]
Something like this [diff](https://github.com/jeffgrunewald/stargate/commit/50de5570a85e5ea582756139837d22380c72ee38)

**Comment by BrendanBall** [comment]
Hey @jeffgrunewald thanks for responding :)

Yes that mostly makes sense.
Regarding backwards compatibility, can you explain how you're currently using this library to produce messages? Because this is how I currently have to do it which looks like the only way:

```elixir
    Stargate.Producer.Supervisor.start_link(stargate_config(config, registry))
    registry_key = :"sg_prod_#{tenant}_#{namespace}_#{topic}"

    Stargate.Producer.produce(
      {:via, Registry, {:my_custom_registry, registry_key}},
      message
    )
```

Is this the correct way to do it? If it is, that means the registry_key atom is part of the public api even though it isn't documented, which means that if you change it to be a 4-tuple, it'll break existing uses of this library. Since this library is at version 0.1.x that doesn't necessarily matter and it's up to you, but I'm just pointing this out.
This is why I think there should be a public api that returns the registry key e.g.:

```elixir
    Stargate.Producer.Supervisor.start_link(stargate_config(config, :my_custom_registry))
    registry_key = Stargate.Producer.registry_key(tenant, namespace, topic)

    Stargate.Producer.produce(
      {:via, Registry, {:my_custom_registry, registry_key}},
      message
    )
```

Regarding the new registry_key:
> I like the suggestion of the names being 4-tuples; if I understand your suggestion I think we'd want the first element of the tuple to be the type of process as an atom (:producer, :consumer, :reader) and the remaining three elements being the tenant, namespace, and topic as simple strings.

Yes I think this makes sense. It's probably possible to get away with the tenant and namespace to be converted to atoms, I'm not sure if there's a use case where the number of tenants and namespaces could cause problems in this case, but I would probably just keep it simple and therefore as strings. I'm not sure if this would have any noticible performance impact.
While we're on this, I noticed that persistence isn't part of the registry key, so it's possible to have a clash if you have 2 topics e.g. `persistent://public/default/foo` and `non-persistent://public/default/foo` since they currently use the same registry key.

PS: In your diff, I assume you just did it quickly but `{:producer_ack, "#{state.tenant}", "#{state.namespace}", "#{state.topic}"}` can probably just be ` {:producer_ack, state.tenant, state.namespace, state.topic}`?

Also, I'm still pretty new to Elixir so if something I say doesn't make sense, let me know :)

**Comment by jeffgrunewald** [comment]
Your point is well taken; you're correct that I have made the assumption that the library user can determine the needed addressing information based on the pattern I outlined for the process names and I did this in doing a lot of manual testing watching these named processes in the Observer during the initial testing but looking from your perspective I can appreciate this is not a great interface.

Your point is also well taken about the persistent vs. non-persistent topics sharing the same registry information under the current strategy. I had not considered the possibility a user might want to have both a persistent and non-persistent topic with the rest of the naming schema being the same but as this is supported by Pulsar I feel it should be supported by Stargate as well.

I would like to make producing and finding the topic as easy as possible and reduce the amount of boiler plate to a bare minimum. To that end, what would be your reaction to a helper function with a similar interface but that returns the full via-tuple for addressing the producer process?

Simple example, using defaults:
```
iex (1)> {:ok, supervisor_pid} = Stargate.Producer.Supervisor.start_link(stargate_config(config))
iex (2)> registry_key = Stargate.Producer.registry_key(tenant, namespace, topic)
{:via, Registry, {:sg_reg_default, {:producer, "persistent", tenant, namespace, topic}}

iex (3)> :ok = Stargate.Producer.produce(registry_key, messages)
```

Custom example, with additional config supplied by the user:
```
iex (1)> {:ok, supervisor_pid} = Stargate.Producer.Supervisor.start_link(stargate_config(config, :custom_registry))
iex (2)> registry_key = Stargate.Producer.registry_key(tenant, namespace, topic, name: :custom_registry, persistence: :nonpersistent)
{:via, Registry, {:sg_reg_custom_registry, {:producer, "nonpersistent", tenant, namespace, topic}}

iex (3)> :ok = Stargate.Producer.produce(registry_key, messages)
```

In this case, we support addressing to both persistent and non-persistent topics but we assume the default "persistent" as is the policy of Pulsar itself. It also allows the user to assume the default registry name if you won't have a complex supervision strategy spanning multiple top-level supervisors and registry processes but does allow you to override if your use calls for that level of complexity.

I can document the expected top-level supervisor and the registry process names better so as to ensure the user has an easier time finding that the names will all be prepended with `sg_reg_` and `sg_sup_` but I feel it's playing it safer to continue with this practice where these names are concerned to ensure they are properly namespaced to avoid the user accidentally creating name collisions in their app with other processes they create.

I appreciate your input.

**Comment by jeffgrunewald** [comment]
Another question for you: based on your experience with the library, would you feel there's a use case for returning a registry key for other processes than the producer process? To locate the `{:via, Registry, {:sg_reg_default, {:producer_ack, "persistent", "tenant", "namespace", "topic"}}}` for instance?

In that event, would your inclination be to make that part of the arguments to the registry_key helper function as well or append it as another option and default to assuming the caller is looking for the producer unless otherwise noted?

**Comment by jeffgrunewald** [comment]
Also, to answer your question about string-interpolating the tenant, namespace, and topic elements of the via-tuple, I should take another look at all the ways those elements of the topic config are handled once supplied by the user, but since they're just passed directly to the producer/receiver config there's nothing stopping the user from supplying a value that _doesn't_ implement String.Chars so I felt during that first pass it was slightly "safer" to ensure that these values are handled to convert them to strings at runtime. Perhaps though this isn't as important now that we're relying more on via-tuples for addressing these processes. I'll have to think about that.

**Comment by BrendanBall** [comment]
Thanks for your feedback. It addresses most of my concerns.
I've done some more investigation though and even though the above looks sensible, I think the most flexible solution would be following the conventions of [GenServer Name registration](https://hexdocs.pm/elixir/1.12/GenServer.html#module-name-registration). 
This simply means that you should allow a `name` to be passed to `Stargate.Producer.start_link`. This is the most flexible and imo easiest solution. I don't see that Stargate references the producer internally, so it doesn't look like this should be a problem.
We'll still need to change any internal atom names that have topics in them into tuples though.
Regarding other processes, I'm not sure whether it's necessary to access `producer_ack`.
Currently the only other process that might need to be accessible is the consumer process for async acks.
We're currently only doing sync acks, but the message handler does allow you to return `:continue` instead of `:ack`, in which case I'm currently not sure how you ack later then. If you can access the consumer then you can do `Stargate.Receiver.ack(receiver, message_id)` where `receiver` would be the name passed in to `Stargate.Receiver.start_link`. This one might be a problem though because it is referenced in the library internally.

So my solution currently looks like:
1. Change all process names with `#{topic}` in them into tuples where the topic stays a string.
2. Allow the library consumer to pass in a `name` to `Stargate.Producer.start_link`
3. Allow the library consumer to pass in a `name` to `Stargate.Receiver.start_link` (however this is less important for us right now so could be done separately)

**Comment by jeffgrunewald** [comment]
I'm comfortable with via tuples and helper functions to make generating and working with those tuples more ergonomic but I hesitate to allow arbitrary naming of the processes via a `:name` for a couple of reasons:
* I worry about confusion between the BEAM process `name` and the Pulsar producer/consumer `name` parameter which has very different semantics and imposes controls on those operations the user should really be very sure about before invoking
* This is technically possible for the producer process but the consumer genstage pipeline needs to be able to determine the names of the other processes in order to establish the genstage subscriptions
* I think a consistent naming strategy across all processes makes it easier to reason about the state of the system so letting some processes receive arbitrary names while others receive deterministic via-tuples could lead to confusion. You could always set up a name relay, performing a name-to-tuple lookup decoupled from the library; it's a little more work to set up but that decoupling allows for the most flexibility

**Comment by BrendanBall** [comment]
ok that's fine, makes sense. Then I'd be happy with `Stargate.Producer.registry_key` and `Stargate.Receiver.registry_key`.

**Comment by jeffgrunewald** [comment]
Addressed by https://github.com/jeffgrunewald/stargate/pull/23
