### ISSUE TITLE
Doc : How to start many producer processes

### ISSUE THREAD

**Issue by chainix** [jeffgrunewald/stargate#27]
Hi,

In my project I had the requirement to start many producer processes when starting `Stargate.Supervisor` but in the documentation there was no indication on how to do it. So I went thourg the `Stargate.Supervisor` code source and I found out that the function `start_producer` could iterate over multiple producer configs :  

```java
 [
      name: :pulsar_app,
      host: [{"localhost", 8080}],
      producer: [
            [
              persistence: "persistent",
              tenant: "bricoshop",
              namespace: "carpentry",
              topic: "events"
            ],
            [
              persistence: "persistent",
              tenant: "partshop",
              namespace: "engine",
              topic: "events"
            ]
      ]
]
```
this works well but I'was wondering if there is another way to do it ? I think it is better to add it to the documentation.

Thanks

**Comment by jeffgrunewald** [comment]
Thanks for the suggestion and glad the configuration you needed worked for you. I did update the documentation on the producer module to include this as a supported configuration: 12f2e1cd83bee409768c7e17c631033e602728db
